server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:chapter_97;MODE=MySQL;
    username: root
    password: 12341234
    driver-class-name: org.h2.Driver

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  config: classpath:logback-spring-local.xml

